tasks:
  - name: Script Task
    init: echo 'init script'
    command: echo 'start script'

  - name: Install Foundry Task
    init: echo 'Test'

ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview
